
services:
  ruoyi-app:
    image: openjdk:8u342-jre
    ports:
      - 8080:8080
    networks:
      - ruoyi-net
    volumes:
      - /home/jack/Desktop/Toolset/docker/app/ruoyi-admin.jar:/usr/local/src/ruoyi-admin.jar
    command: [
      "java",
      "-jar",
      "/usr/local/src/ruoyi-admin.jar"
      ]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    depends_on:
      ruoyi-db: 
        condition: service_healthy

    
    
  ruoyi-db:
    image: mysql:5.7
    networks:
      - ruoyi-net
    volumes:
      - /home/jack/Desktop/Toolset/docker/app/sql:/docker-entrypoint-initdb.d 
      - /home/jack/Desktop/Toolset/docker/app/ruoyi-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=ry
      - MYSQL_ROOT_PASSWORD=123456
    command: [
      "--skip-character-set-client-handshake",
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci"
      ]
    healthcheck:
      test: ["CMD", "mysqladmin","ping","-h","localhost","-u","root","-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  ruoyi-data:

networks:
  ruoyi-net: